pub mod agent_cli;
pub mod agent_tools;
pub mod child_env;
pub mod file_watch;
pub mod files;
pub mod git;
pub mod ide;
pub mod indexer;
pub mod jsonl;
pub mod mcp_wire;
pub mod media_server;
// macOS only: the menu exists to give up `Cmd+W` (ADR-0046). Nothing to build
// on Linux, where the same actions are renderer hotkeys.
#[cfg(target_os = "macos")]
pub mod menu;
pub mod osc_title;
pub mod profiles;
pub mod reveal;
pub mod routines;
pub mod search;
pub mod sessions;
pub mod settings;
pub mod shell_path;
pub mod sops;
pub mod terminal;
pub mod updates;
pub mod watcher;
pub mod webview_health;
pub mod wsl;
